### PR TITLE
Feature/20

### PR DESCRIPTION
**Pull request by Paola351**
Closes Issue #20

### CODE REVIEW

**Comment by Paola351** [comment]
Please, if you can, add the label hacktoberfest-accepted when you'll merge this :D

**Review by kagof — CHANGES_REQUESTED** [review]
Hi @Paola351, thanks a lot for the PR!

The `editSprite.sh` script can be used to resize the larger sprites (Kyogre, Groudon, Rayquaza, Deoxys) down so they'll fit a bit better.

For example, with groudon: `./editSprite.sh groudon 32` makes it a more appropriate size.

Could you resize those sprites so they will fit in the progress bar? Ideally, there should be no part of the sprites that overlap the edge of the progress bar.

**Comment by Paola351** [comment]
> Hi @Paola351, thanks a lot for the PR!
> 
> The `editSprite.sh` script can be used to resize the larger sprites (Kyogre, Groudon, Rayquaza, Deoxys) down so they'll fit a bit better.
> 
> For example, with groudon: `./editSprite.sh groudon 32` makes it a more appropriate size.
> 
> Could you resize those sprites so they will fit in the progress bar? Ideally, there should be no part of the sprites that overlap the edge of the progress bar.
> 
> Also, as a bit of a nitpick, could you please move the Jirachi sprite 1 pixel to the right, and 1 pixel down? That way none of the progress bar colour shows in front of the sprite

Deoxys is already 32x32, I'll apply the changes you requested to the other pokemons :D

**Comment by Paola351** [comment]
please @kagof let me know it there's something wrong

**Review by kagof — CHANGES_REQUESTED** [review]
Hi @Paola351, sorry for the belated review here, I've been away.

I think some clarification is needed RE gif sizing - although the gifs used in the plugin are generally 32x32 pixels, the actual space we have to work with in the progress bar is a bit smaller - the height of the progress bar is closer to 18px. So for sprites of smaller Pokémon (eg Jirachi), they fit fine as the full 32 pixels isn't utilized. However for Deoxys, some of the Pokémon is cut off, as you can see in this screenshot:
Screenshot 2020-10-17 at 20 58 55

The editSprite.sh script I've created lets you "shrink" the sprite, then pad the border to make it 32x32 again. So, for example, I've done this with Blastoise, which is why the gif looks sort of blurry: 


I'm not sure what the errors are that you're getting with the editSprite.sh script - we could potentially try to work through them and get the script working for you, or you could try to find an alternative to it.

As far as the other sprites go:

1. Kyogre isn't even showing up for me: possibly shifted off of the drawing area entirely?
Screenshot 2020-10-17 at 21 17 14

1. Groudon is almost not visible:
Screenshot 2020-10-17 at 20 56 18

1. Rayquaza is also not showing up for me, again possibly shifted off of the drawing area entirely?
Screenshot 2020-10-17 at 21 21 32


1. Jirachi could be shifted down and to the right, see currently:
Screenshot 2020-10-17 at 21 05 47
vs desired:
Screenshot 2020-10-17 at 21 06 39

**Comment by Paola351** [comment]
> Hi @Paola351, sorry for the belated review here, I've been away.
> 
> I think some clarification is needed RE gif sizing - although the gifs used in the plugin are generally 32x32 pixels, the actual space we have to work with in the progress bar is a bit smaller - the height of the progress bar is closer to 18px. So for sprites of smaller Pokémon (eg Jirachi), they fit fine as the full 32 pixels isn't utilized. However for Deoxys, some of the Pokémon is cut off, as you can see in this screenshot:
> Screenshot 2020-10-17 at 20 58 55
> 
> The editSprite.sh script I've created lets you "shrink" the sprite, then pad the border to make it 32x32 again. So, for example, I've done this with Blastoise, which is why the gif looks sort of blurry:
> 
> 
> I'm not sure what the errors are that you're getting with the editSprite.sh script - we could potentially try to work through them and get the script working for you, or you could try to find an alternative to it.
> 
> As far as the other sprites go:
> 
> 1. Kyogre isn't even showing up for me: possibly shifted off of the drawing area entirely?
>    Screenshot 2020-10-17 at 21 17 14
> 2. Groudon is almost not visible:
>    Screenshot 2020-10-17 at 20 56 18
> 3. Rayquaza is also not showing up for me, again possibly shifted off of the drawing area entirely?
>    Screenshot 2020-10-17 at 21 21 32
> 4. Jirachi could be shifted down and to the right, see currently:
>    Screenshot 2020-10-17 at 21 05 47
>    vs desired:
>    Screenshot 2020-10-17 at 21 06 39

Is there anyway i can see the loading panel without installing the plugin? I use intellij idea 2019.3.4. 
I'll try to solve the problem you described.

**Comment by Paola351** [comment]
@kagof I fixed the comments

**Review by kagof — CHANGES_REQUESTED** [review]
Hi @Paola351 thanks again for the changes.

Kyogre is perhaps a bit too small and too high:

Screenshot 2020-10-27 at 18 05 22

And I would prefer it if `xShift` and `yShift` were reverted back to `final` fields and the setters were removed; there's no reason for these to be changed at runtime, and the setters are never used.

I'm requesting these 2 changes before I merge this into develop, however as it is nearly there and you've been very patient, I'm marking this PR as `hacktoberfest-accepted` so you can still get your hacktoberfest credit for this issue. Thanks!

**Review by kagof — APPROVED** [review]

**Pull request merged**
