### PR TITLE
added testGui

### PR DESCRIPTION
**Pull request by Paola351**
I managed to add the TestGui even here.  
I think the PokemonResourceLoader is a little bit inefficient as everythin the paint is called, the method have to load the gif. I restored the previous version of the Pokemon class with the icons variables.  
Let me know if this can help and, as said in the other PR, please mark it with hacktoberfest-accepted.
@kagof

### CODE REVIEW

**Comment by Paola351** [comment]
@kagof only 20 hours left.....

**Review by kagof — COMMENTED** [review]
Hi @Paola351,

> I think the PokemonResourceLoader is a little bit inefficient as everythin the paint is called, the method have to load the gif.

If you look at the implementation of `IconLoader`, it already has caching of icons built in, so it does not need to load the gif from disc every time `paint` is called. However, even if that was the case, the change you've made still calls `IconLoader` every time `paint` is called, as it just reverted back to my previous lazy loading implementation. As such, I'd prefer if this were reverted back to the version using `PokemonResourceLoader`, as there the concerns are separated, and we could easily implement our own caching, etc, if desired.


That being said, I'm unable to actually start your `TestBar.main` method. When attempting to run it with Gradle I get

```
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: com/google/common/collect/ImmutableList
	at com.kagof.intellij.plugins.pokeprogress.Pokemon.<init>(Pokemon.java:107)
	at com.kagof.intellij.plugins.pokeprogress.Pokemon.<init>(Pokemon.java:99)
	at com.kagof.intellij.plugins.pokeprogress.Pokemon.<clinit>(Pokemon.java:17)
	at com.kagof.intellij.plugins.pokeprogress.TestBar.<init>(TestBar.java:25)
	at com.kagof.intellij.plugins.pokeprogress.TestBar$4.run(TestBar.java:133)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.ImmutableList
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.ImmutableList

	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more
```

Can you tell me your run configuration for this?

I have more comments to make about this, however I think they are moot if I can't get it up and running

**Comment by kagof** [comment]
I've also redirected this into the `develop` branch, as no new work should be done against the release branches unless it is fixing bugs in a currently supported version

**Comment by Paola351** [comment]
I had the same problem. I didn't add that dependency (Immutable list was used with your version too). I send you a picture of how I run the program.  
Schermata 2020-11-06 alle 00 32 58

**Comment by kagof** [comment]
Hi @Paola351, I've adapted this code in a [separate branch](https://github.com/kagof/intellij-pokemon-progress/pull/32), in a way that I seem to be able to run without issues. It also uses reflection to adjust the x/y values instead of having them as mutable fields.

I tried adapting this branch to to use my changes, but unfortunately with all of the changes (removing PokemonResourceLoader, etc) it was just a bit difficult. So I'm afraid for now I'm just going to close this PR and accept the one that I have raise. However, I have credited you in the CONTRIBUTING guidelines for this change.

Thank you so much for the work on this, it is a great idea that is very helpful!

**Pull request closed without merging**
