### PR TITLE
Add optional flat progress bar themes

### LINKED ISSUE #59: Possibility of having multiple themes for the gradient
**Current behaviour (optional)**

There are some options to change the look, but none that affect the color gradient.

**Description of the desired feature (required)**

Since there are many possibilities of how the gradient could look, there could be a drop-down with a few predefined themes.

**Why this feature would be valuable (optional)**

Purely personal choice of aesthetics.

**Additional information or context (optional)**

I experimented with what looks I would prefer personally, and came up with a "Dark Flat" theme that uses the dark color of the types:

obrazek

Another option could be just "Flat" that uses the middle color:

obrazek

or "Light Flat":

obrazek

### PR DESCRIPTION
**Pull request by chylex**
I added the theme option above the checkbox panel as a labelled form component, seemed the easiest. Let me know if you'd like it somewhere else.

obrazek

obrazek

Closes #59.

### CODE REVIEW

**Comment by chylex** [comment]
Hmm, looks like GitHub CI's JDK 8 is having issues with some syntax. Want me to fix compilation on JDK 8, or can you update it to JDK 11?

**Comment by kagof** [comment]
That location for the dropdown seems goodto me.

I tried upgrading this repo to JDK 11 about a year ago, and it caused the plugin not to work on Android Studio: https://github.com/kagof/intellij-pokemon-progress/issues/35. Although I'd expect that Android Studio has fixed compatibility now, I'd want to do some testing before releasing something including this upgrade. Would you be able to fix compilation for JDK 8, please?

**Comment by chylex** [comment]
Seems OK now.

**Review by kagof — APPROVED** [review]
This looks good @chylex! Thanks so much for submitting it.

**Pull request merged**
