### PR TITLE
added requested starters

### PR DESCRIPTION
**Pull request by Paola351**
Added requested pokemons.
Solved #17

### CODE REVIEW

**Comment by kagof** [comment]
Hi @Paola351, thanks a lot for the PR!

The `editSprite.sh` script can be used to resize the larger sprites (Kyogre, Groudon, Rayquaza, Deoxys) down so they'll fit a bit better.

For example, with groudon: `./editSprite.sh groudon 32` makes it a more appropriate size.

Could you resize those sprites so they will fit in the progress bar? Ideally, there should be no part of the sprites that overlap the edge of the progress bar.

**Review by kagof — CHANGES_REQUESTED** [review]
Hi @Paola351 thanks for another great PR!

I have a couple of change requests for this one as well.

1. As with the other PR, I'd appreciate it if you could resize the larger sprites (Torterra, Infernape, and Empoleon) so they fit within the borders of the progress bar

2. Could you please shift Piplup up a little bit, so its feet are visible?

3. I've noticed that these sprites seem to be moving a bit faster than the existing ones - the existing sprites have a delay of 50ms between frames, it would be nice if you could make these ones match that (the editSprite.sh script will do this automatically)

Thanks again!

**Comment by Paola351** [comment]
> Hi @Paola351 thanks for another great PR!
> 
> I have a couple of change requests for this one as well.
> 
> 1. As with the other PR, I'd appreciate it if you could resize the larger sprites (Torterra, Infernape, and Empoleon) so they fit within the borders of the progress bar
> 2. Could you please shift Piplup up a little bit, so its feet are visible?
> 3. I've noticed that these sprites seem to be moving a bit faster than the existing ones - the existing sprites have a delay of 50ms between frames, it would be nice if you could make these ones match that (the editSprite.sh script will do this automatically)
> 
> Thanks again!

Torterra, Infernape, and Empoleon seems to be 32x32, it is not the right size?
I shifted Piplup and slowed a little bit the gifs, as you requested. I can't use directly imagemagik though... I hope it's good anyway ^^

**Comment by Paola351** [comment]
please @kagof let me know it there's something else i can do

**Review by kagof — CHANGES_REQUESTED** [review]
Hi @Paola351, thanks for the changes!

Turtwig & Chimchar both look good to me, however Piplup could still be shifted up by quite a bit:
Screenshot 2020-10-17 at 21 29 49

Similarly to your other PR, the 3 larger Pokémon are going outside of the drawing area and getting cut off, so they need to be resized to fit the height better.

see Torterra:
Screenshot 2020-10-17 at 21 28 10

Infernape:
Screenshot 2020-10-17 at 21 32 48

and Empoleon:
Screenshot 2020-10-17 at 21 33 39

Thanks again!

**Review by kagof — APPROVED** [review]

**Pull request merged**
